### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by Arinerron** [Arinerron/ScratchAPI#1]
# Features to be done:

These are features that will be done in the future (hopefully). The bold ones are the ones I'm hoping I can get done ASAP.

---
- [ ] **Register users programmatically**
- [ ] **Programmatically set project contents and create new projects**
- [ ] **Thumbnail set function for projects and users**
- [x] Modify cloud data
- [ ] Get list of featured projects
- [ ] Get list of newest projects
- [ ] Get list of curated projects
- [ ] Get list of team members (?)
- [ ] Get list of top-remixed projects
- [ ] Get list of top-loved projects
- [ ] Get list of featured studios
- [ ] Get current project curator
- [ ] Get Scratch design studio
- [ ] Get list of projects by following
- [ ] Get list of projects by following's loved projects
- [ ] Get list of projects in studios I'm following
- [ ] Toggle comments on a project
- [ ] Change project description, notes, draft, etc
- [ ] **API for manipulating and getting info from studios**
- [x] API for fetching statistics
- [x] Get user description
- [x] Get what I am working on
- [x] Get location
- [ ] Get status (Scratcher, New Scratcher, Team Member, etc) 
- [ ] Get recent project listing
- [ ] Get loved project and their count, and favorite project's count
- [ ] Get followers and following list
- [ ] Get comments on user's profile in a List<ScratchComment>
- [ ] Scratch Comment reporting, deleting, etc.
- [ ] Get user manager as a ScratchUserManager?

---
- [ ] Better documentation
- [ ] **API Examples**

**Comment by Arinerron** [comment]
3 years later: @as-com Yeah, good idea. I'm banned though, so development on this project has slowed down. A lot.

**Comment by Laphatize** [comment]
my boy
